### PR TITLE
Fix wasm, add wasm ci check, move files around to distinguish native and wasm code.

### PR DESCRIPTION
**Pull request by expenses**
Sorry, I missed this!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
@expenses oh it seems WASM is still failing.

**Comment by expenses** [comment]
Is there a way to refresh the CI? I think it should work now.

**Comment by expenses** [comment]
@yoshuawuyts should  be good to go now. Sorry about all that. If you're not happy with removing `-Dwarnings` on CI then we should move things around so we don't have `#[cfg(not(all(target_arch = "wasm32", feature = "wasm-bindgen")))]
` everywhere.

**Comment by expenses** [comment]
@yoshuawuyts What do you think?

**Pull request merged**
